{
 "title": "Oncall Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_http\", instance=\"oncall-web:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{job=\"blackbox_tcp\", instance=\"oncall-web:8080\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{job=\"blackbox_icmp\", instance=\"oncall-web:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "limit": "10" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Custom metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "oncall_teams_quantity", "legendFormat": "__auto" },
    { "expr": "oncall_users_quantity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "dissect.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}