global:
  scrape_interval: "10s"
  scrape_timeout: "5s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: "prometheus"
    dns_sd_configs:
      - names:
          - oncall-web
        type: A
        port: 8081
  - job_name: "nodeexporter"
    static_configs:
      - targets:
          - "node-exporter:9100"